version: '3.7'
services:
  web:
    container_name: django_web
    build: api
    volumes:
      - ./api:/code

    command: python code/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - api/.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ffp_dev

  frontend:
    restart: always
    command: npm start
    container_name: front
    volumes:
      - ./frontend:/code/frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - web
    networks:
      - db-net

volumes:
  postgres_data:

networks:
  db-net:
    driver: bridge