# Generated by Django 3.2.7 on 2021-09-11 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_rename_mealdeyset_mealdayset'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='mealdayset',
            name='day_set',
        ),
        migrations.RemoveField(
            model_name='mealdayset',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='userdayset',
            name='day_set',
        ),
        migrations.RemoveField(
            model_name='userdayset',
            name='user',
        ),
        migrations.DeleteModel(
            name='ActivityDaySet',
        ),
        migrations.DeleteModel(
            name='DaySet',
        ),
        migrations.DeleteModel(
            name='MealDaySet',
        ),
        migrations.DeleteModel(
            name='UserDaySet',
        ),
    ]
